[SERVICE]
    Flush        1
    Log_Level    warn
    Parsers_File /fluent-bit/etc/parsers.conf
    HTTP_Server  On
    HTTP_Listen  0.0.0.0
    HTTP_Port    2020

[INPUT]
    Name              syslog
    Mode              udp
    Listen            0.0.0.0
    Port              5140
    Parser            campus_syslog
    Buffer_Chunk_Size 64k
    Buffer_Max_Size   256k

[FILTER]
    Name         parser
    Match        *
    Key_Name     message
    Parser       campus_json
    Reserve_Data On

[OUTPUT]
    Name        loki
    Match       *
    Host        loki
    Port        3100
    Labels      job=campus-erp
    Label_Keys  $service,$level
    Line_Format json
