[PARSER]
    Name   campus_syslog
    Format regex
    Regex  ^<(?<pri>\d+)>(?:[A-Z][a-z]{2} [ \d]\d \d{2}:\d{2}:\d{2} )?(?:(?<ident>[\w-]+): )?(?<message>.*)$

[PARSER]
    Name   campus_json
    Format json
