import json
import logging
import signal
import threading
from functools import partial

from prometheus_client import Gauge, start_http_server

from packages.campus_common.config import load_settings
from packages.campus_common.database import Database
from packages.campus_common.events import consume_forever, pending_count, relay_forever
from packages.campus_common.http import configure_logging
from services.finance.app.domain.billing import ENROLLMENT_CONFIRMED, handle_enrollment_event
from services.finance.app.domain.payments import expire_stale_intents
from services.finance.app.domain.reports import run_monthly_schedule
from services.finance.app.models import OutboxEvent

log = logging.getLogger("campus.finance.worker")


def main() -> None:
    settings = load_settings("finance")
    configure_logging("finance-worker", settings.log_host)
    database = Database(settings.database_url)
    stop = threading.Event()
    for code in (signal.SIGTERM, signal.SIGINT):
        signal.signal(code, lambda *_: stop.set())
    backlog = Gauge("campus_outbox_pending", "Committed events not yet published", ["service"])
    reports = Gauge("campus_monthly_reports_generated_total", "Monthly reports generated by the scheduler", ["service"])
    start_http_server(9100)
    for target, args in ((relay_forever, (database, OutboxEvent, settings.broker_url, stop)),
                         (consume_forever, (settings.broker_url, "finance.enrollment-billing", (ENROLLMENT_CONFIRMED,),
                                            partial(handle_enrollment_event, database), stop))):
        threading.Thread(target=target, args=args, daemon=True).start()
    log.info(json.dumps({"service": "finance-worker", "event": "started"}))
    generated = 0
    while not stop.is_set():
        try:
            expired = expire_stale_intents(database)
            created = run_monthly_schedule(database)
            generated += len(created)
            reports.labels("finance").set(generated)
            backlog.labels("finance").set(pending_count(database, OutboxEvent))
            if expired or created:
                log.info(json.dumps({"service": "finance-worker", "event": "scheduled_jobs", "expired_intents": expired,
                                     "reports": [f"{tenant}:{period}" for tenant, period in created]}))
        except Exception as error:  # noqa: BLE001 - keep scheduling across transient database failures
            log.error(json.dumps({"service": "finance-worker", "event": "schedule_failed", "reason": repr(error)}))
        stop.wait(30)


if __name__ == "__main__":
    main()
